// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id and email \u2014 useful to verify the MCP connection is authenticated as the right operator.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = { user_id: ctx.getUserId(), email: ctx.getUserEmail(), client_id: ctx.getClientId() };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool2({
  name: "list_clients",
  title: "List clients",
  description: "List clients belonging to the signed-in TCL operator.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("clients").select("id, name, email, phone, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "List projects",
  description: "List installation/integration projects for the signed-in operator.",
  inputSchema: {
    status: z2.string().optional().describe("Optional status filter (e.g. active, completed)."),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let query = supabase.from("projects").select("id, name, status, client_id, budget, start_date, end_date, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-service-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_service_orders_default = defineTool4({
  name: "list_service_orders",
  title: "List service orders",
  description: "List service orders (tickets) for the signed-in operator, newest first.",
  inputSchema: {
    status: z3.string().optional().describe("Optional status filter (open, in_progress, closed)."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let query = supabase.from("service_orders").select("id, title, status, priority, client_id, project_id, description, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { service_orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-service-order.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var create_service_order_default = defineTool5({
  name: "create_service_order",
  title: "Create service order",
  description: "Create a new service order (support/install ticket) for the signed-in operator.",
  inputSchema: {
    title: z4.string().trim().min(1).describe("Short title of the ticket."),
    description: z4.string().optional().describe("Detailed description of the issue or work."),
    priority: z4.enum(["low", "medium", "high", "urgent"]).optional(),
    client_id: z4.string().uuid().optional().describe("Optional client UUID to link the ticket to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, priority, client_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("service_orders").insert({
      user_id: ctx.getUserId(),
      title,
      description: description ?? null,
      priority: priority ?? "medium",
      status: "open",
      client_id: client_id ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created service order ${data.id}` }],
      structuredContent: { service_order: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "earjplippbonusveefjh";
var mcp_default = defineMcp({
  name: "tcl-platform-mcp",
  title: "TCL Platform MCP",
  version: "0.1.0",
  instructions: "Tools for TCL Tech Solutions operators. Read clients, projects, and service orders, and create new service orders. All calls run as the signed-in user under row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_clients_default,
    list_projects_default,
    list_service_orders_default,
    create_service_order_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
