// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://celsjaflmxthwqlkoevs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlbHNqYWZsbXh0aHdxbGtvZXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDY2NzEsImV4cCI6MjA3MjQyMjY3MX0.iDIfbt7YTaX0Erarf5waAyc_QwL_cOfwq-5AYGcaMGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});