// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqwbkvcxoppfoihjvtbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxd2JrdmN4b3BwZm9paGp2dGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODYyNDMsImV4cCI6MjA2Mjc2MjI0M30.FoAXIfmCkjP0Dw4MGAIwzs9Xrgv8fiKJBlpeZXlUq14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);